# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.

options:
  cert:
    description: Certificate filepath.
    type: string
    default: "/var/snap/glauth/common/etc/glauth/certs.d/glauth.crt"
  config:
    description: Configuration directory for GLAuth.
    type: string
    default: "/var/snap/glauth/common/etc/glauth/glauth.d"
  key:
    description: Key filepath.
    type: string
    default: "/var/snap/glauth/common/etc/glauth/keys.d/glauth.key"
  domain:
    description: LDAP domain.
    type: string
    default: 
  ldap-default-bind-dn:
    description: Default bind DN for LDAP operations.
    type: string
    default:
  ldap-password:
    description: LDAP password.
    type: string
    default:
  ldap-search-base:
    description: Default base DN for ldap operations.
    type: string
    default:
