# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.

options:
  domain:
    description: LDAP domain.
    type: string
    default: 
  ldap-search-base:
    description: Default base DN for ldap operations.
    type: string
    default:
